// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V21_populateGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V21_populateGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "202101140752512_V2.1_populateGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
