// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V11_addIsSubscribedToNewsletterToCustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V11_addIsSubscribedToNewsletterToCustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "202101140635528_V1.1_addIsSubscribedToNewsletterToCustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
